Repository WildCodeSchool-2023-09/JS-RemoteFR-SACOD-P2-Vogue-Merry, pull requests merged in 2023-11, with the labels that each got.

#62 S03 Fix Modal Login
  frontend/src/App.scss
  frontend/src/components/Card.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Modal/Login.jsx
  frontend/src/components/NavBar.jsx
  frontend/src/main.jsx
  frontend/src/pages/Leaderboard.jsx
Labels: REVIEWED

#66 (MERGE EN 2️⃣) S03-US05 : Leaderboard
  frontend/src/components/Trophy.jsx
  frontend/src/pages/Leaderboard.jsx
  frontend/src/pages/leaderboard.scss
Labels: REVIEWED

#69 (MERGE EN 3️⃣) S03-US08 : Animation de composant
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.scss
  frontend/src/components/Card.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Ingredients.jsx
  frontend/src/components/Jeu.jsx
  frontend/src/components/OngletElixir.jsx
  frontend/src/pages/Leaderboard.jsx
  frontend/src/pages/leaderboard.scss
Labels: REVIEWED

#70 fixe de la page de jeu et retrait des console.info
  frontend/src/components/Jeu.jsx
Labels: REVIEWED

#71 S03 US08 - Onglet contact
  frontend/src/App.scss
  frontend/src/components/Footer.jsx
  frontend/src/components/Modal/Contact.jsx
Labels: REVIEWED

#72 FIXCSS URGENT 😱
  frontend/src/App.scss
  frontend/src/components/Footer.jsx
Labels: REVIEWED

#77 S04-US03 : Modal apparait correctement lors d'une recherche
  frontend/src/components/Card.jsx
  frontend/src/components/Modal/CardModal.jsx
  frontend/src/components/OngletElixir.jsx
Labels: REVIEWED

#76 S04US02-Système de vie
  frontend/src/App.scss
  frontend/src/components/Ingredients.jsx
  frontend/src/components/Jeu.jsx
Labels: REVIEWED, CORRECTIONS DONE

#79 S04-US01 : Bouton desactivé une fois cliqué
  frontend/src/components/Ingredients.jsx
  frontend/src/components/Jeu.jsx
Labels: REVIEWED

#83 redaction des regles
  frontend/src/App.scss
  frontend/src/components/Rules.jsx
Labels: REVIEWED

#84 S04 US07 : Ecran de Victoire/Défaite
  frontend/src/App.scss
  frontend/src/components/Card.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Ingredients.jsx
  frontend/src/components/Jeu.jsx
  frontend/src/components/Modal/CardModal.jsx
  frontend/src/components/Modal/Contact.jsx
  frontend/src/components/OngletElixir.jsx
  frontend/src/components/Victory.jsx
Labels: REVIEWED

#85 S04 us04
  frontend/src/App.scss
  frontend/src/components/Ingredients.jsx
  frontend/src/components/Jeu.jsx
Labels: REVIEWED

#86 S04 US08 :
  frontend/src/components/OngletElixir.jsx
  frontend/src/components/Rules.jsx
Labels: REVIEWED

#87 fix css 😱
  frontend/src/App.scss
  frontend/src/components/Footer.jsx
  frontend/src/components/Jeu.jsx
  frontend/src/components/OngletElixir.jsx
Labels: REVIEWED

#92 S04-US08 : Limitation Onglet Elixir
  frontend/src/components/OngletElixir.jsx
  frontend/src/components/Rules.jsx
Labels: REVIEWED

#97 S04-US12 : Onglet Elixir : Bouton Disabled quand on est dessus
  frontend/src/components/OngletElixir.jsx
Labels: REVIEWED

#94 S04-US08 : ONGLET VRAIMENT FINI
  frontend/src/components/OngletElixir.jsx
Labels: REVIEWED

#95 S04 us10
  frontend/src/App.scss
  frontend/src/components/Jeu.jsx
Labels: REVIEWED

#98 S04 us12
  README.md
Labels: REVIEWED

#101 fixjeu
  frontend/src/components/Jeu.jsx
  frontend/src/components/Victory.jsx
Labels: REVIEWED

#102 S04-US05 : Bouton en couleur différente si bon ingrédients ou pas
  frontend/src/components/Ingredients.jsx
Labels: REVIEW REQUESTED

#106 S04 u sbonus bouton try again + boutton play sur regles
  frontend/src/components/Rules.jsx
  frontend/src/components/Victory.jsx
Labels: REVIEWED

#107 Modal Card peut etre fermé quand on clique dehors et avec Echap aussi + Début localstorage (pas du tout fonctionnel pour l'instant)
  frontend/src/components/Accueil.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Modal/CardModal.jsx
  frontend/src/components/OngletElixir.jsx
  frontend/src/components/Victory.jsx
Labels: REVIEWED

#108 S05 us02
  frontend/src/App.scss
  frontend/src/assets/chaudron.png
  frontend/src/components/NavBar.jsx
Labels: REVIEWED

#110 LocalStorage du BestScore fait
  frontend/src/components/Jeu.jsx
  frontend/src/components/Victory.jsx
Labels: REVIEWED

#111 changement d'image bg mobile
  frontend/src/App.scss
  frontend/src/assets/classmobile.png
Labels: REVIEWED

#112 FIX CSS + IMPORT
  frontend/src/App.scss
  frontend/src/assets/parch.png
  frontend/src/components/Accueil.jsx
  frontend/src/components/Ingredients.jsx
  frontend/src/components/Jeu.jsx
  frontend/src/components/NavBar.jsx
Labels: REVIEWED
